name: "JF-CLI: Package"
on:
  push:
    branches: 
      - '**'
permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read
  security-events: write # Required for uploading code scanning.
env:
  JF_RT_URL: "https://${{vars.JF_NAME}}.jfrog.io"
  JOB_SUMMARY: false
  JFROG_CLI_LOG_LEVEL: DEBUG # DEBUG, INFO, WARN, ERROR
  DEFAULT_WORKSPACE: "${{github.workspace}}" 
  BUILD_ID: "${{github.run_number}}.0"
  BUILD_NAME: "flask-webgoat" 
  MODULE_NAME: "webgoat"
  REPO_VIRTUAL: "flask-webgoat-virtual"
  REPO_LOCAL: "flask-webgoat-init-local"
  REPO_REMOTE: "pypi-remote"

jobs:
  pyPackage: 
    name: "Package"
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: "${{env.DEFAULT_WORKSPACE}}"
    steps:
        - name: "Setup JFrog CLI"
          uses: jfrog/setup-jfrog-cli@v5
          id: jfrog-cli
          env:
            JF_URL: ${{env.JF_RT_URL}}
            JFROG_CLI_LOG_LEVEL: "DEBUG"
            JF_GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}  
          with:
            version: latest 
            oidc-provider-name: ${{vars.JF_OIDC_PROVIDER_NAME}}
            disable-job-summary: ${{env.JOB_SUMMARY}}

        - name: Checkout
          uses: actions/checkout@v6 

        - name: "Folder list"
          run: | 
              tree .

        - name: "JF Show"
          run: | 
              jf c s

        - name: "Setup Summary"
          run: |
            echo "# :frog: Setup Summary :pushpin:" >> $GITHUB_STEP_SUMMARY
            echo " " >> $GITHUB_STEP_SUMMARY
            echo " " >> $GITHUB_STEP_SUMMARY
            echo " - Installed JFrog CLI [$(jf --version)](https://jfrog.com/getcli/) " >> $GITHUB_STEP_SUMMARY
            echo "    - $(jf --version) " >> $GITHUB_STEP_SUMMARY
            echo "    - $(pip3 -V) " >> $GITHUB_STEP_SUMMARY
            echo " " >> $GITHUB_STEP_SUMMARY
            echo " " >> $GITHUB_STEP_SUMMARY

        - name: "Create pip config"
          run: |
            jf pipc --repo-resolve=${{env.REPO_VIRTUAL}} --repo-deploy=${{env.REPO_VIRTUAL}}

        - name: "Pip install"
          run: |
            jf pip install -r requirements.txt --build-name ${{env.BUILD_NAME}} --build-number ${{env.BUILD_ID}}

        - name: "Publish build info"
          run: |
            jf rt bce ${{env.BUILD_NAME}} ${{env.BUILD_ID}} 
            jf rt bag ${{env.BUILD_NAME}} ${{env.BUILD_ID}}  
            jf rt bad ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --module="${{env.MODULE_NAME}}" "${BAD_DEPS_DIR}/*"
            jf rt bp ${{env.BUILD_NAME}} ${{env.BUILD_ID}} --detailed-summary=true 
      